cMcglynnShoppingApp/Models/CodeFirst/Item.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace cMcglynnShoppingApp.Models.CodeFirst
{
    public class Item
    {
        public int Id { get; set; }
        public DateTime CreationDate { get; set; }
        public DateTime? UpdatedDate { get; set; }
        public string Name { get; set; }
        public decimal Price { get; set; }
        public string MediaURL { get; set; }
        [AllowHtml]
        public string Description { get; set; }
        
    }
}

cMcglynnShoppingApp/Controllers/CartItemsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using cMcglynnShoppingApp.Models;
using cMcglynnShoppingApp.Models.CodeFirst;
using Microsoft.AspNet.Identity;

namespace cMcglynnShoppingApp.Controllers
{
    public class CartItemsController : Universal
    {
        

        // GET: CartItems      
        [Authorize]
        public ActionResult Index()
        {   
            var user = db.Users.Find(User.Identity.GetUserId());// GRABS THE CURRENT USER OBJECT
            return View(user.CartItems.ToList());// THIS WILL DISPLAY ONLY THE USERS CART ITEMS
        }

        // GET: CartItems/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            CartItem cartItem = db.CartItems.Find(id);
            if (cartItem == null)
            {
                return HttpNotFound();
            }
            return View(cartItem);
        }

        // GET: CartItems/Create
        [Authorize(Roles = "Admin")]
        public ActionResult Create()
        {
            return View();
        }

        // POST: CartItems/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        // id taken from id = item.id from Items index page
        public ActionResult Create(int? id)
            // BEGINING OF WHAT WE DID IN SCHOOL
        {   // to make sure its a good request
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Item item = db.Items.Find(id);
            if (item == null)
            {
                return HttpNotFound();
            }
            // this is the actual code that adds the items to the cart
            var user = db.Users.Find(User.Identity.GetUserId());

            if (user.CartItems.Any(c => c.ItemId == id))
            {
                var existingCartItem = user.CartItems.FirstOrDefault(c => c.ItemId == id);
                existingCartItem.Count += 1;
                db.SaveChanges();
            }
            else
            {
                CartItem cartitem = new CartItem();
                cartitem.Count = 1;
                cartitem.ItemId = id.Value;
                cartitem.created = System.DateTime.Now;
                cartitem.CustomerId = user.Id;
                db.CartItems.Add(cartitem);
                db.SaveChanges();
            }

            return RedirectToAction("Index", "Items");          
        }
        // END OF WHAT WE ACTUALLY DID IN SCHOOL TO ADD ITEMS TO CART
        // GET: CartItems/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            CartItem cartItem = db.CartItems.Find(id);
            if (cartItem == null)
            {
                return HttpNotFound();
            }
            return View(cartItem);
        }

        // POST: CartItems/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "Id,ItemId,CustomerId,Count,created,MediaURL")] CartItem cartItem)
        {
            if (ModelState.IsValid)
            {

                db.Entry(cartItem).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(cartItem);
        }

        // GET: CartItems/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            CartItem cartItem = db.CartItems.Find(id);
            if (cartItem == null)
            {
                return HttpNotFound();
            }
            return View(cartItem);
        }

        // POST: CartItems/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            CartItem cartItem = db.CartItems.Find(id);
            db.CartItems.Remove(cartItem);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

cMcglynnShoppingApp/Controllers/ItemsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using cMcglynnShoppingApp.Models;
using cMcglynnShoppingApp.Models.CodeFirst;
using System.IO;

namespace cMcglynnShoppingApp.Controllers
{

    public class ItemsController : Universal
    {


        // GET: Items
        public ActionResult Index()
        {
            return View(db.Items.ToList());
        }
        // GET: Items
        public ActionResult SearchResults(string searchItem)
        {
            return View(db.Items.Where(i => i.Name.Contains(searchItem) || i.Description.Contains(searchItem)).ToList());
        }

        // GET: Items/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Item item = db.Items.Find(id);
            if (item == null)
            {
                return HttpNotFound();
            }
            return View(item);
        }

        // GET: Items/Create
        [Authorize(Roles = "Admin")]
        public ActionResult Create()
        {
            return View();
        }

        // POST: Items/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [Authorize(Roles = "Admin")]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "Id,CreationDate,UpdatedDate,Name,Price,MediaURL,Description")] Item item, HttpPostedFileBase image)
        {
            if (image != null && image.ContentLength > 0)  //CODE TO BE ABLE TO UPLOAD IMAGES
            {
                var ext = Path.GetExtension(image.FileName).ToLower();
                if (ext != ".png" && ext != ".jpg" && ext != ".jpeg" && ext != ".gif" && ext != ".bmp")
                    ModelState.AddModelError("image", "Invalid Format.");
            }
            if (ModelState.IsValid)
            {
                var filePath = "/Upload/";   //UPLOADING IMAGES TO DATABASE AND PHYSICAL LOCATION "FOLDER"
                var absPath = Server.MapPath("~" + filePath);
                item.MediaURL = filePath + image.FileName;
                image.SaveAs(Path.Combine(absPath, image.FileName));

                item.CreationDate = System.DateTime.Now;
                db.Items.Add(item);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(item);
        }

        // GET: Items/Edit/5
        [Authorize(Roles = "Admin")]
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Item item = db.Items.Find(id);
            if (item == null)
            {
                return HttpNotFound();
            }
            return View(item);
        }

        // POST: Items/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [Authorize(Roles = "Admin")]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "Id,CreationDate,UpdatedDate,Name,Price,MediaURL,Description")] Item item, string mediaURL, HttpPostedFileBase image)
        {
            if (image != null && image.ContentLength > 0)  //CODE TO BE ABLE TO UPLOAD IMAGES
            {
                var ext = Path.GetExtension(image.FileName).ToLower();
                if (ext != ".png" && ext != ".jpg" && ext != ".jpeg" && ext != ".gif" && ext != ".bmp")
                    ModelState.AddModelError("image", "Invalid Format.");
            }
            if (ModelState.IsValid)
            {
                db.Entry(item).State = EntityState.Modified;
                if (image != null)
                {
                    var filePath = "/Upload/";   //UPLOADING IMAGES TO DATABASE AND PHYSICAL LOCATION "FOLDER"
                    var absPath = Server.MapPath("~" + filePath);
                    item.MediaURL = filePath + image.FileName;
                    image.SaveAs(Path.Combine(absPath, image.FileName));
                }
                else
                {
                    item.MediaURL = mediaURL;

                }

                item.UpdatedDate = System.DateTime.Now;
                
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(item);
        }

        // GET: Items/Delete/5
        [Authorize(Roles = "Admin")]
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Item item = db.Items.Find(id);
            if (item == null)
            {
                return HttpNotFound();
            }
            return View(item);
        }

        // POST: Items/Delete/5
        [Authorize(Roles = "Admin")]
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Item item = db.Items.Find(id);
            var absPath = Server.MapPath("~" + item.MediaURL);  //DELETES IMAGE FROM FOLDER
            System.IO.File.Delete(absPath);                     //DELETES IMAGE FROM FOLDER
            db.Items.Remove(item);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

cMcglynnShoppingApp/Views/Items/Create.cshtml
@model cMcglynnShoppingApp.Models.CodeFirst.Item
<div style="padding-left:120px; font:bolder; font-family:'Franklin Gothic Book';">
    @{
        ViewBag.Title = "Create";
    }

    <h2>Create</h2>

    @*ENABLE IMAGE UPLOAD*@
    @using (Html.BeginForm("Create", "Items", FormMethod.Post, new { enctype = "Multipart/form-data" }))
    {
        @Html.AntiForgeryToken()

        <div class="form-horizontal">
            <h4>Item</h4>
            <hr />
            @Html.ValidationSummary(true, "", new { @class = "text-danger" })
            @*<div class="form-group">
                @Html.LabelFor(model => model.CreationDate, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.CreationDate, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.CreationDate, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.UpdatedDate, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.UpdatedDate, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.UpdatedDate, "", new { @class = "text-danger" })
                </div>
            </div>*@

            <div class="form-group">
                @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.Price, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.Price, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.Price, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                <label class="control-label col-md-2">Upload Image</label>
               
                <div class="col-md-10">
                   <input name="image" type="file" class="form-control" />  @*INPUT TO UPLOAD IMAGES*@
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.Description, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    <textarea id="editor" class="form-control" name="Description" rows="5"></textarea>
                    @Html.ValidationMessageFor(model => model.Description, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                <div class="col-md-offset-2 col-md-10">
                    <input type="submit" value="Create" class="btn btn-danger" />
                </div>
            </div>
        </div>
    }

    <div>
        <button style="border-radius: 8px;border: 2px solid white; margin-top:2px;" class="w3-button w3-ripple w3-blue">@Html.ActionLink("Back to List", "Index")</button>
    </div>

    @section Scripts {
        @Scripts.Render("~/bundles/jqueryval")
        <script src="~/Scripts/tinymce/tinymce.min.js"></script>
        <script src="~/Scripts/tinymce/jquery.tinymce.min.js"></script>
        <script type="text/javascript">
            $(function () {
                tinymce.init({
                    selector: '#editor'
                });
            });
        </script>
    }

</div>

cMcglynnShoppingApp/Views/Items/Details.cshtml
@model cMcglynnShoppingApp.Models.CodeFirst.Item
<div style="margin-left:330px; font:bolder; font-family:'Franklin Gothic Book';">
    @{
        ViewBag.Title = "Details";
    }

    <h2>Details</h2>

    <div>
        <h4>@Model.Name</h4>
        <img src="@Model.MediaURL"/>
        <hr />
        <dl class="dl-horizontal">
            
            <dt>
                @Html.DisplayNameFor(model => model.CreationDate)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.CreationDate)
            </dd>

            <dt>
                @Html.DisplayNameFor(model => model.UpdatedDate)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.UpdatedDate)
            </dd>

            <dt>
                @Html.DisplayNameFor(model => model.Name)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.Name)
            </dd>

            <dt>
                @Html.DisplayNameFor(model => model.Price)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.Price)
            </dd>

            <dt>
                @Html.DisplayNameFor(model => model.MediaURL)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.MediaURL)
            </dd>

            <dt>
                @Html.DisplayNameFor(model => model.Description)
            </dt>
            

            <dd>
                @*"RAW" TO MAKE THE DESCRIPTION TEXT APPEAR WITHOUT HTML <P> TAGS*@
                @Html.Raw(Model.Description)
            </dd>

        </dl>

    </div>
    
    @*<img src="@item.Item.MediaURL" style="max-width:60px" />*@
    @using (Html.BeginForm("Create", "CartItems", new { id = Model.Id }, FormMethod.Post))
    {    //To keep secure
        @Html.AntiForgeryToken()
        //input type button
        <input type="submit" style="border-radius: 8px;" class="w3-button w3-ripple w3-black" value="Add to cart" /><i class="fa fa-shopping-cart"></i>
    }
    @*<iframe width="420" height="315"
            src="https://www.youtube.com/embed/sEBdUiQx6_k?autoplay=1"></iframe>*@
    
    <p>
        <div style="display:inline-flex">
            <button style="border-radius: 8px;border: 2px solid white; margin-top:2px;" class="w3-button w3-ripple w3-blue">@Html.ActionLink("Edit", "Edit", new { id = Model.Id })</button>
            <button style="border-radius: 8px;border: 2px solid white; margin-top:2px;" class="w3-button w3-ripple w3-blue">@Html.ActionLink("Delete", "Delete", new { id = Model.Id })</button>
        </div>
        
        <button style="border-radius: 8px;border: 2px solid white; margin-top:2px; " class="w3-button w3-ripple w3-blue">@Html.ActionLink("Back to List", "Index")</button>
      
    </p>
</div>

cMcglynnShoppingApp/Views/Items/Index.cshtml
@model IEnumerable<cMcglynnShoppingApp.Models.CodeFirst.Item>    
@*IENUMERABLE FILTERS THROUGH WHATS PASSED THROUGH IT AND CREATES A LIST*@

<div class="row">
    <div class="w3-main" style="margin-left:330px">
        
        @*"CREATE LINK" ONLY VISIBLE IF LOGGED IN AS ADMIN*@
        @if (User.IsInRole("Admin"))
        {
            <div style="padding-left:15px; margin-top:8px;margin-bottom:8px;">
                
                <button style="border-radius: 8px;border: 2px; margin-top:2px; solid white;" class="w3-button w3-ripple w3-black">@Html.ActionLink("Create New ", "Create")</button>
            </div>
        }

       
        @foreach (var item in Model)
        {
            <div class="col-md-3">
                @*MAKES THE PICTURE OF THE ITEM LINK TO THE "DETAILS" PAGE*@
                <a href="@Url.Action("Details", "Items" , new { id = item.Id })">
                    <img src="@Url.Content(item.MediaURL)" />
                </a>

                <div style="padding-top:20px;padding-bottom:10px;text-shadow:1px 1px 0 #444">
                    <p>@item.Name</p>
                    <p>@item.Price</p>
                      @*// CODE TO ADD ITEMS TO CART also begining of "FORM"*@
                    @using (Html.BeginForm("Create", "CartItems", new { id = item.Id }, FormMethod.Post))
                    {    //To keep secure
                        @Html.AntiForgeryToken()
                        //input type button
                        <input type="submit" style="border-radius: 8px;"  class="w3-button w3-ripple w3-black " value="Add to cart" /><i class="fa fa-shopping-cart"></i>

                    }
                   
                </div>

                @if (User.IsInRole("Admin"))
                {
                    <div style="display:inline-flex">
                        <button style="border-radius: 8px;border: 2px solid white; margin-top:2px;" class="w3-button w3-ripple w3-blue">@Html.ActionLink("Edit", "Edit", new { id = item.Id })</button>
                        <button style="border-radius: 8px;border: 2px solid white; margin-top:2px;" class="w3-button w3-ripple w3-blue">@Html.ActionLink("Delete", "Delete", new { id = item.Id })</button>
                       
                    </div>
                }

            </div>


        }

    </div>
    </div>

    @*<div class="col-md-3">
            <img src="~/Assets/watches images/m2.jpg" />
            <div style="padding-top:20px;padding-bottom:10px;text-shadow:1px 1px 0 #444">
                <p>CFW-187</p>
                <p>$1990.00</p>
                <button class="w3-button w3-ripple w3-black">Buy</button>
            </div>
        </div>
        <div class="col-md-3">
            <img src="~/Assets/watches images/m3.jpg" />
            <div style="padding-top:20px;padding-bottom:10px;text-shadow:1px 1px 0 #444">
                <p>CFW-221</p>
                <p>$1099.00</p>
                <button class="w3-button w3-ripple w3-black">Buy</button>
            </div>
        </div>
        <div class="col-md-3">
            <img src="~/Assets/watches images/m5.jpg" />
            <div style="padding-top:20px;padding-bottom:10px;text-shadow:1px 1px 0 #444">
                <p>CFW-220</p>
                <p>$3220.00</p>
                <button class="w3-button w3-ripple w3-black">Buy</button>
            </div>
        </div>*@
@*</div>*@

<!--end second row-->
<!--start third row-->
@*<div class="row">
        <div class="col-md-3">
            <img src="~/Assets/watches images/m6.jpg" />
            <div style="padding-top:20px;padding-bottom:0px;text-shadow:1px 1px 0 #444">
                <p>CFW-550</p>
                <p>$1550.00</p>
                <button class="w3-button w3-ripple w3-black">Buy</button>
            </div>
        </div>
        <div class="col-md-3">
            <img src="~/Assets/watches images/m7.jpg" />
            <div style="padding-top:20px;padding-bottom:0px;text-shadow:1px 1px 0 #444">
                <p>CFW-650</p>
                <p>$2500.00</p>
                <button class="w3-button w3-ripple w3-black">Buy</button>
            </div>
        </div>
        <div class="col-md-3">
            <img src="~/Assets/watches images/m8.jpg" />
            <div style="padding-top:20px;padding-bottom:0px;text-shadow:1px 1px 0 #444">
                <p>CFW-920</p>
                <p>$1990.00</p>
                <button class="w3-button w3-ripple w3-black">Buy</button>
            </div>
        </div>
        <div class="col-md-3">
            <img src="~/Assets/watches images/m9.jpg" />
            <div style="padding-top:20px;padding-bottom:0px;text-shadow:1px 1px 0 #444">
                <p>CFW-234</p>
                <p>$3550.00</p>
                <button class="w3-button w3-ripple w3-black">Buy</button>
            </div>
        </div>
    </div>*@
<!--end third row-->

cMcglynnShoppingApp/Views/Items/Index2.cshtml
@model IEnumerable<cMcglynnShoppingApp.Models.CodeFirst.Item>

@{
    ViewBag.Title = "Index";
}

<h2>Index</h2>

<p>
    @Html.ActionLink("Create New", "Create")
</p>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.CreationDate)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.UpdatedDate)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Name)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Price)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.MediaURL)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Description)
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.CreationDate)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.UpdatedDate)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Name)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Price)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.MediaURL)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Description)
        </td>
        <td>
            @Html.ActionLink("Edit", "Edit", new { id=item.Id }) |
            @Html.ActionLink("Details", "Details", new { id=item.Id }) |
            @Html.ActionLink("Delete", "Delete", new { id=item.Id })
        </td>
    </tr>
}

</table>

cMcglynnShoppingApp/Views/Items/SearchResults.cshtml
@model IEnumerable<cMcglynnShoppingApp.Models.CodeFirst.Item>      


<div class="row">
    <div class="w3-main" style="margin-left:330px">
        @if (User.IsInRole("Admin"))
        {
            <div style=" padding-left:15px;">

                <button style="border-radius: 8px;margin-top:8px;margin-bottom:8px;border: 2px solid white;" class="w3-button w3-ripple w3-black">@Html.ActionLink("Create New ", "Create")</button>
            </div>
        }


        @foreach (var item in Model)
        {
            <div class="col-md-6" style="margin-top:20px;">
                <a href="@Url.Action("Details", "Items" , new { id = item.Id })">
                    <img src="@item.MediaURL" />
                </a>
                
                <div style="padding-top:20px;padding-bottom:10px;text-shadow:1px 1px 0 #444;">
                    <p>@item.Name</p>
                    <p>@item.Price</p>
                    @using (Html.BeginForm("Create", "CartItems", new { id = item.Id }, FormMethod.Post))
                    {    //To keep secure
                        @Html.AntiForgeryToken()
                        //input type button
                        <input type="submit" style="border-radius: 8px;" class="w3-button w3-ripple w3-black" value="Add to cart" />
                    
                    
                    }
                    <div class="jumbotron" style="margin-left:580px;background-color:white;padding-bottom:0px;">
                        <iframe width="420" height="315"
                                src="https://www.youtube.com/embed/sEBdUiQx6_k?autoplay=1"></iframe>
                    </div>
                </div>
                    
                @if (User.IsInRole("Admin"))
                {
                    <div style="display:inline-flex">
                        <button style="border-radius: 8px;border: 2px; margin-top:2px; solid white;" class="w3-button w3-ripple w3-blue">@Html.ActionLink("Edit", "Edit", new { id = item.Id })</button>
                        <button style="border-radius: 8px;border: 2px; margin-top:2px; solid white;" class="w3-button w3-ripple w3-blue">@Html.ActionLink("Delete", "Delete", new { id = item.Id })</button>
                    </div>
                }

            </div>


        }

    </div>
</div>

@*<div class="col-md-3">
        <img src="~/Assets/watches images/m2.jpg" />
        <div style="padding-top:20px;padding-bottom:10px;text-shadow:1px 1px 0 #444">
            <p>CFW-187</p>
            <p>$1990.00</p>
            <button class="w3-button w3-ripple w3-black">Buy</button>
        </div>
    </div>
    <div class="col-md-3">
        <img src="~/Assets/watches images/m3.jpg" />
        <div style="padding-top:20px;padding-bottom:10px;text-shadow:1px 1px 0 #444">
            <p>CFW-221</p>
            <p>$1099.00</p>
            <button class="w3-button w3-ripple w3-black">Buy</button>
        </div>
    </div>
    <div class="col-md-3">
        <img src="~/Assets/watches images/m5.jpg" />
        <div style="padding-top:20px;padding-bottom:10px;text-shadow:1px 1px 0 #444">
            <p>CFW-220</p>
            <p>$3220.00</p>
            <button class="w3-button w3-ripple w3-black">Buy</button>
        </div>
    </div>*@
@*</div>*@

<!--end second row-->
<!--start third row-->
@*<div class="row">
        <div class="col-md-3">
            <img src="~/Assets/watches images/m6.jpg" />
            <div style="padding-top:20px;padding-bottom:0px;text-shadow:1px 1px 0 #444">
                <p>CFW-550</p>
                <p>$1550.00</p>
                <button class="w3-button w3-ripple w3-black">Buy</button>
            </div>
        </div>
        <div class="col-md-3">
            <img src="~/Assets/watches images/m7.jpg" />
            <div style="padding-top:20px;padding-bottom:0px;text-shadow:1px 1px 0 #444">
                <p>CFW-650</p>
                <p>$2500.00</p>
                <button class="w3-button w3-ripple w3-black">Buy</button>
            </div>
        </div>
        <div class="col-md-3">
            <img src="~/Assets/watches images/m8.jpg" />
            <div style="padding-top:20px;padding-bottom:0px;text-shadow:1px 1px 0 #444">
                <p>CFW-920</p>
                <p>$1990.00</p>
                <button class="w3-button w3-ripple w3-black">Buy</button>
            </div>
        </div>
        <div class="col-md-3">
            <img src="~/Assets/watches images/m9.jpg" />
            <div style="padding-top:20px;padding-bottom:0px;text-shadow:1px 1px 0 #444">
                <p>CFW-234</p>
                <p>$3550.00</p>
                <button class="w3-button w3-ripple w3-black">Buy</button>
            </div>
        </div>
    </div>*@
<!--end third row-->